Core_Almacen/Core_Almacen/Models/Almacen.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Core_Almacen.Models
{
    public class Almacen
    {
        [Key]
        public int Empid { get; set; }

        [Required(ErrorMessage = "*Campo obligatorio")]
        [Display(Name = "Producto")]
        public string Producto { get; set; }

        [Required(ErrorMessage = "*Campo obligatorio")]
        [Display(Name = "Marca")]
        public string Marca { get; set; }

        [Required(ErrorMessage = "*Campo obligarotio (no más de 50)")]
        [Display(Name = "Cantidad")]
        [Range(20, 50)]
        public int Cantidad { get; set; }

        [Required(ErrorMessage = "*Campo obligatorio")]
        [Display(Name = "Fecha de llegada")]
        public string Llegada { get; set; }

        [Required(ErrorMessage = "*Campo obligatorio")]
        [Display(Name = "Fecha de caducidad")]
        public string Caducidad { get; set; }

     
    }
}

Core_Almacen/Core_Almacen/Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Core_Almacen.Models
{
    public class ApplicationDbContext : DbContext
    {

        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {
        }
        public DbSet<Almacen> Almacen { get; set; }
    }
}

Core_Almacen/Core_Almacen/Models/ErrorViewModel.cs
using System;

namespace Core_Almacen.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Core_Almacen/Core_Almacen/Controllers/AlmacenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Core_Almacen.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Core_Almacen.Controllers
{
    public class AlmacenController : Controller
    {

        private readonly ApplicationDbContext _db;

        public AlmacenController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            var displaydata = _db.Almacen.ToList();
            return View(displaydata);
        }

        [HttpGet]
        public async Task<IActionResult> Index(string empSearch)
        {
            ViewData["GetAlmacenDetails"] = empSearch;
            var empquery = from x in _db.Almacen select x;
            if (!String.IsNullOrEmpty(empSearch))
            {
                empquery = empquery.Where(x => x.Producto.Contains(empSearch) || x.Marca.Contains(empSearch));
            }
            return View(await empquery.AsNoTracking().ToListAsync());
        }

        public IActionResult Create()
        {
            return View();  
        }

        [HttpPost]
        public async Task<IActionResult> Create(Almacen nEmp)
            { 
            if (ModelState.IsValid)
            {
                _db.Add(nEmp);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");  

            }

            return View(nEmp);  
        }

        public async Task<ActionResult> Detail(int? id) 
        {
            if (id == null)
            {
                return RedirectToAction("Index");

            }

            var getEmpDetail = await _db.Almacen.FindAsync(id);
            return View(getEmpDetail);
        }


        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            var getEmpDetail = await _db.Almacen.FindAsync(id);
            return View(getEmpDetail);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Almacen oldEmp)
        {
            if (ModelState.IsValid)
            {
                _db.Update(oldEmp);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(oldEmp);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            var getEmpDetail = await _db.Almacen.FindAsync(id);
            return View(getEmpDetail);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var getEmpDetail = await _db.Almacen.FindAsync(id);
            _db.Almacen.Remove(getEmpDetail);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

    }
}

Core_Almacen/Core_Almacen/Views/Almacen/Create.cshtml
@model Core_Almacen.Models.Almacen

@{
    ViewData["Title"] = "Create";
}

<h1>NUEVO PRODUCTO</h1>

<h4>Almacen</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Producto" class="control-label"></label>
                <input asp-for="Producto" class="form-control" />
                <span asp-validation-for="Producto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" class="form-control" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cantidad" class="control-label"></label>
                <input asp-for="Cantidad" class="form-control" />
                <span asp-validation-for="Cantidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Llegada" class="control-label"></label>
                <input asp-for="Llegada" class="form-control" />
                <span asp-validation-for="Llegada" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Caducidad" class="control-label"></label>
                <input asp-for="Caducidad" class="form-control" />
                <span asp-validation-for="Caducidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar al inicio</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Core_Almacen/Core_Almacen/Views/Almacen/Delete.cshtml
@model Core_Almacen.Models.Almacen

@{
    ViewData["Title"] = "Delete";
}


<h3>¿ESTÁ SEGURO DE ELIMINARLO?</h3>
<div>
    <h4>Almacen</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Empid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Empid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Producto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Producto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Marca)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cantidad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Llegada)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Llegada)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Caducidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Caducidad)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index">Regresar al inicio</a>
    </form>
</div>

Core_Almacen/Core_Almacen/Views/Almacen/Detail.cshtml
@model Core_Almacen.Models.Almacen

@{
    ViewData["Title"] = "Detail";
}

<h1>DETALLES</h1>

<div>
    <h4>Almacen</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Empid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Empid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Producto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Producto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Marca)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cantidad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Llegada)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Llegada)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Caducidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Caducidad)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Empid }) |
    <a asp-action="Index">Regresar al inicio</a>
</div>

Core_Almacen/Core_Almacen/Views/Almacen/Edit.cshtml
@model Core_Almacen.Models.Almacen

@{
    ViewData["Title"] = "Edit";
}

<h1>EDITAR</h1>

<h4>Almacen</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Empid" class="control-label"></label>
                <input asp-for="Empid" class="form-control" readonly />
                <span asp-validation-for="Empid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Producto" class="control-label"></label>
                <input asp-for="Producto" class="form-control" />
                <span asp-validation-for="Producto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" class="form-control" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cantidad" class="control-label"></label>
                <input asp-for="Cantidad" class="form-control" />
                <span asp-validation-for="Cantidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Llegada" class="control-label"></label>
                <input asp-for="Llegada" class="form-control" />
                <span asp-validation-for="Llegada" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Caducidad" class="control-label"></label>
                <input asp-for="Caducidad" class="form-control" />
                <span asp-validation-for="Caducidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar al inicio</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Core_Almacen/Core_Almacen/Views/Almacen/Index.cshtml
@model IEnumerable<Core_Almacen.Models.Almacen>

@{
    ViewData["Title"] = "Index";
}

<h1>Inicio</h1>

<p>
    <a asp-action="Create">Nuevo producto</a>
</p>
<form asp-action="Index" method="get">
    <p>
        <input type="search" placeholder="Ingresa producto o marca: " name="empSearch"
               value="@ViewData["GetAlmacenDetails"]" style="width:500px;" />
        <input type="submit" value="Buscar" class="btn btn-primary" />
        <a asp-action="Index"> Ver todos</a>
    </p>

</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Empid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Producto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Marca)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cantidad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Llegada)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Caducidad)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Empid)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Producto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Marca)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cantidad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Llegada)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Caducidad)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.Empid }, new { @class = "btn btn-primary" }) |
                @Html.ActionLink("Detalles", "Detail", new { id = item.Empid }, new { @class = "btn btn-success" }) |
                @Html.ActionLink("Eliminar", "Delete", new { id = item.Empid }, new { @class = "btn btn-danger" })
            </td>
        </tr>
}
    </tbody>
</table>

Core_Almacen/Core_Almacen/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Core_Almacen</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        body {
            background-color: #d1cdd1;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Almacen" asp-action="Index"> ALMACEN "CRUZ"</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Almacen" asp-action="Index"></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; Curso Everis 2020 - <a asp-area="" asp-controller="Almacen" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>